### PR TITLE
Changed Logging Preference to Hubitat Driver Standard txtEnable

### PR DESCRIPTION
**Pull request by ucdscott**
Replaced loggingEnabled with txtEnable to conform with built-in drivers and consolidate Hubitat Preference Manager entries for better user experience

### CODE REVIEW

**Comment by lgkahn** [comment]
> Replaced loggingEnabled with txtEnable to conform with built-in drivers and consolidate Hubitat Preference Manager entries for better user experience

This is obsolete so mo longer maintained. Get the new version.

**Comment by ucdscott** [comment]
Where can I find the new version?

**Comment by lgkahn** [comment]
hubitat package manager or on the thread on the hubitat website.. search form sendmail v3

---- Original Message ----

**Comment by augoisms** [comment]
@ucdscott @lgkahn This driver is not obsolete.

You can find the current version here:
https://github.com/augoisms/hubitat/blob/master/rainforest-eagle/rainforest-eagle.driver.groovy

@ucdscott Regarding the PR. This driver doesn't support descriptive text logging. Descriptive text logging is different than the type of logging that this driver uses, which is more of the "debug" kind. If there is a universal consensus for a debug logging parameter I'll consider updating all my drivers.

**Comment by ucdscott** [comment]
The native Hubitat drivers use 'Enable debug logging' (name:logEnable) for debug logs.

**Comment by lgkahn** [comment]
thats not a driver i wrote.. 

---- Original Message ----

**Comment by ucdscott** [comment]
@lgkahn It appears you're responding on the incorrect thread. I submitted similar pull requests to both you and augoisms.

**Pull request closed without merging**
